
// Generated by Cadence Encounter(R) RTL Compiler v12.10-p006_1

// Verification Directory fv/led_top 

module key_filter_1(clk, rst_n, key, key_stable, key_flag);
  input clk, rst_n, key;
  output key_stable, key_flag;
  wire clk, rst_n, key;
  wire key_stable, key_flag;
  wire [14:0] cnt;
  wire [1:0] state;
  wire [2:0] key_r;
  wire en_cnt, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_93;
  DFFQX1 \cnt_reg[11] (.CK (clk), .D (n_87), .Q (cnt[11]));
  NOR2XL g1717(.A (n_93), .B (n_86), .Y (n_87));
  DFFQX1 \cnt_reg[14] (.CK (clk), .D (n_85), .Q (cnt[14]));
  DFFQX1 \cnt_reg[10] (.CK (clk), .D (n_84), .Q (cnt[10]));
  XNOR2XL g1720(.A (cnt[11]), .B (n_79), .Y (n_86));
  NOR2XL g1721(.A (n_93), .B (n_83), .Y (n_85));
  NOR2XL g1722(.A (n_93), .B (n_80), .Y (n_84));
  DFFQX1 \cnt_reg[13] (.CK (clk), .D (n_81), .Q (cnt[13]));
  AOI21XL g1724(.A0 (cnt[14]), .A1 (n_75), .B0 (n_82), .Y (n_83));
  DFFQX1 \cnt_reg[9] (.CK (clk), .D (n_78), .Q (cnt[9]));
  NOR2XL g1726(.A (cnt[14]), .B (n_75), .Y (n_82));
  NOR2XL g1727(.A (n_93), .B (n_77), .Y (n_81));
  MXI2XL g1728(.A (n_1), .B (cnt[10]), .S0 (n_71), .Y (n_80));
  NOR2XL g1729(.A (n_1), .B (n_71), .Y (n_79));
  NOR2XL g1730(.A (n_93), .B (n_73), .Y (n_78));
  DFFQX1 \cnt_reg[12] (.CK (clk), .D (n_74), .Q (cnt[12]));
  AOI21XL g1732(.A0 (cnt[13]), .A1 (n_68), .B0 (n_76), .Y (n_77));
  DFFQX1 \cnt_reg[8] (.CK (clk), .D (n_70), .Q (cnt[8]));
  NOR2XL g1734(.A (cnt[13]), .B (n_68), .Y (n_76));
  NAND2BX1 g1735(.AN (n_68), .B (cnt[13]), .Y (n_75));
  NOR2XL g1736(.A (n_93), .B (n_69), .Y (n_74));
  AOI21XL g1737(.A0 (cnt[9]), .A1 (n_64), .B0 (n_72), .Y (n_73));
  NOR2XL g1738(.A (cnt[9]), .B (n_64), .Y (n_72));
  NAND2BX1 g1739(.AN (n_64), .B (cnt[9]), .Y (n_71));
  NOR2XL g1740(.A (n_93), .B (n_67), .Y (n_70));
  XNOR2XL g1741(.A (cnt[12]), .B (n_66), .Y (n_69));
  DFFQX1 \cnt_reg[7] (.CK (clk), .D (n_63), .Q (cnt[7]));
  NAND2XL g1743(.A (cnt[12]), .B (n_66), .Y (n_68));
  AOI21XL g1744(.A0 (cnt[8]), .A1 (n_57), .B0 (n_65), .Y (n_67));
  NOR2XL g1746(.A (n_15), .B (n_57), .Y (n_66));
  NOR2XL g1747(.A (cnt[8]), .B (n_57), .Y (n_65));
  NAND2BX1 g1748(.AN (n_57), .B (cnt[8]), .Y (n_64));
  NOR2XL g1749(.A (n_60), .B (n_93), .Y (n_63));
  DFFSHQX1 key_flag_reg(.SN (rst_n), .CK (clk), .D (n_58), .Q
       (key_flag));
  DFFRHQX1 en_cnt_reg(.RN (rst_n), .CK (clk), .D (n_59), .Q (en_cnt));
  DFFQX1 key_stable_reg(.CK (clk), .D (n_61), .Q (key_stable));
  OAI21X1 g1753(.A0 (n_21), .A1 (n_53), .B0 (n_51), .Y (n_62));
  SDFFRHQX1 \state_reg[1] (.RN (rst_n), .CK (clk), .D (state[1]), .SI
       (state[0]), .SE (n_50), .Q (state[1]));
  DFFQX1 \cnt_reg[6] (.CK (clk), .D (n_55), .Q (cnt[6]));
  OAI21X1 g1756(.A0 (n_3), .A1 (n_52), .B0 (n_17), .Y (n_61));
  AOI21XL g1757(.A0 (cnt[7]), .A1 (n_46), .B0 (n_56), .Y (n_60));
  OAI21XL g1758(.A0 (n_22), .A1 (n_25), .B0 (n_54), .Y (n_59));
  AO22XL g1759(.A0 (key_flag), .A1 (n_52), .B0 (n_6), .B1 (n_50), .Y
       (n_58));
  NAND2BX1 g1760(.AN (n_46), .B (cnt[7]), .Y (n_57));
  NOR2XL g1761(.A (cnt[7]), .B (n_46), .Y (n_56));
  NOR2XL g1762(.A (n_48), .B (n_93), .Y (n_55));
  NAND3X1 g1763(.A (en_cnt), .B (n_25), .C (n_52), .Y (n_54));
  AOI21X1 g1764(.A0 (n_20), .A1 (n_49), .B0 (state[0]), .Y (n_53));
  NAND2XL g1765(.A (n_12), .B (n_50), .Y (n_52));
  OAI211X1 g1766(.A0 (n_20), .A1 (n_7), .B0 (n_5), .C0 (n_50), .Y
       (n_51));
  DFFQX1 \cnt_reg[5] (.CK (clk), .D (n_44), .Q (cnt[5]));
  INVXL g1768(.A (n_50), .Y (n_49));
  NAND2XL g1769(.A (n_27), .B (n_45), .Y (n_50));
  AOI21XL g1770(.A0 (cnt[6]), .A1 (n_40), .B0 (n_47), .Y (n_48));
  NOR2XL g1771(.A (cnt[6]), .B (n_40), .Y (n_47));
  NAND2BX1 g1772(.AN (n_40), .B (cnt[6]), .Y (n_46));
  OAI211X1 g1773(.A0 (cnt[6]), .A1 (n_42), .B0 (cnt[10]), .C0 (n_13),
       .Y (n_45));
  NOR2XL g1774(.A (n_43), .B (n_93), .Y (n_44));
  DFFQX1 \cnt_reg[4] (.CK (clk), .D (n_39), .Q (cnt[4]));
  AOI21X1 g1776(.A0 (cnt[5]), .A1 (n_37), .B0 (n_41), .Y (n_43));
  NAND2XL g1777(.A (n_9), .B (n_37), .Y (n_42));
  NOR2XL g1778(.A (cnt[5]), .B (n_37), .Y (n_41));
  NAND2BX1 g1779(.AN (n_37), .B (cnt[5]), .Y (n_40));
  NOR2XL g1780(.A (n_38), .B (n_93), .Y (n_39));
  DFFQX1 \cnt_reg[3] (.CK (clk), .D (n_35), .Q (cnt[3]));
  AOI21X1 g1782(.A0 (cnt[4]), .A1 (n_30), .B0 (n_36), .Y (n_38));
  DFFQX1 \cnt_reg[1] (.CK (clk), .D (n_34), .Q (cnt[1]));
  DFFQX1 \cnt_reg[2] (.CK (clk), .D (n_33), .Q (cnt[2]));
  NAND2BX1 g1785(.AN (n_30), .B (cnt[4]), .Y (n_37));
  NOR2XL g1786(.A (cnt[4]), .B (n_30), .Y (n_36));
  NOR2XL g1787(.A (n_31), .B (n_93), .Y (n_35));
  NOR2XL g1788(.A (n_11), .B (n_93), .Y (n_34));
  NOR2XL g1789(.A (n_23), .B (n_93), .Y (n_33));
  AOI21XL g1791(.A0 (cnt[3]), .A1 (n_18), .B0 (n_29), .Y (n_31));
  NAND2BX1 g1792(.AN (n_18), .B (cnt[3]), .Y (n_30));
  NOR2XL g1793(.A (cnt[3]), .B (n_18), .Y (n_29));
  NOR2XL g1794(.A (cnt[12]), .B (n_24), .Y (n_28));
  OAI31X1 g1795(.A0 (cnt[12]), .A1 (cnt[13]), .A2 (n_16), .B0
       (cnt[14]), .Y (n_27));
  NOR4X1 g1796(.A (cnt[8]), .B (cnt[6]), .C (n_1), .D (n_0), .Y (n_26));
  MXI2XL g1797(.A (n_20), .B (n_21), .S0 (state[0]), .Y (n_25));
  NAND4XL g1798(.A (cnt[1]), .B (cnt[2]), .C (n_9), .D (n_13), .Y
       (n_24));
  AOI21X1 g1799(.A0 (cnt[2]), .A1 (n_4), .B0 (n_19), .Y (n_23));
  XNOR2XL g1800(.A (key_r[2]), .B (state[1]), .Y (n_22));
  NOR2BX1 g1801(.AN (key_r[1]), .B (key_r[2]), .Y (n_21));
  NOR2BX1 g1802(.AN (key_r[2]), .B (key_r[1]), .Y (n_20));
  NOR2XL g1803(.A (cnt[2]), .B (n_4), .Y (n_19));
  NAND2BX1 g1804(.AN (n_4), .B (cnt[2]), .Y (n_18));
  OAI21X1 g1805(.A0 (n_3), .A1 (n_12), .B0 (key_stable), .Y (n_17));
  DFFQX1 \key_r_reg[2] (.CK (clk), .D (key_r[1]), .Q (key_r[2]));
  DFFQX1 \cnt_reg[0] (.CK (clk), .D (n_14), .Q (cnt[0]));
  CLKINVX1 g1809(.A (n_15), .Y (n_16));
  NAND3BX1 g1810(.AN (n_8), .B (cnt[8]), .C (cnt[10]), .Y (n_15));
  DFFQX1 \key_r_reg[1] (.CK (clk), .D (key_r[0]), .Q (key_r[1]));
  NOR2XL g1812(.A (cnt[0]), .B (n_10), .Y (n_14));
  NOR2BX1 g1813(.AN (cnt[14]), .B (n_8), .Y (n_13));
  OR2X1 g1814(.A (n_7), .B (n_6), .Y (n_12));
  XNOR2XL g1815(.A (cnt[1]), .B (cnt[0]), .Y (n_11));
  DFFQX1 \key_r_reg[0] (.CK (clk), .D (key), .Q (key_r[0]));
  NAND2XL g1817(.A (rst_n), .B (en_cnt), .Y (n_10));
  NOR2XL g1818(.A (cnt[5]), .B (cnt[7]), .Y (n_9));
  NAND2XL g1819(.A (cnt[11]), .B (cnt[9]), .Y (n_8));
  NOR2XL g1820(.A (state[1]), .B (n_2), .Y (n_7));
  INVXL g1821(.A (n_5), .Y (n_6));
  NAND2XL g1822(.A (state[1]), .B (n_2), .Y (n_5));
  NAND2XL g1823(.A (cnt[1]), .B (cnt[0]), .Y (n_4));
  CLKINVX1 g1825(.A (rst_n), .Y (n_3));
  CLKINVX1 g1827(.A (cnt[10]), .Y (n_1));
  NAND4BXL g2(.AN (cnt[13]), .B (cnt[0]), .C (cnt[3]), .D (cnt[4]), .Y
       (n_0));
  AO21X1 g1828(.A0 (n_28), .A1 (n_26), .B0 (n_10), .Y (n_93));
  DFFRX1 \state_reg[0] (.RN (rst_n), .CK (clk), .D (n_62), .Q
       (state[0]), .QN (n_2));
endmodule

module key_filter(clk, rst_n, key, key_stable, key_flag);
  input clk, rst_n, key;
  output key_stable, key_flag;
  wire clk, rst_n, key;
  wire key_stable, key_flag;
  wire [14:0] cnt;
  wire [1:0] state;
  wire [2:0] key_r;
  wire en_cnt, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_93;
  DFFQX1 \cnt_reg[11] (.CK (clk), .D (n_87), .Q (cnt[11]));
  NOR2XL g1717(.A (n_93), .B (n_86), .Y (n_87));
  DFFQX1 \cnt_reg[14] (.CK (clk), .D (n_85), .Q (cnt[14]));
  DFFQX1 \cnt_reg[10] (.CK (clk), .D (n_84), .Q (cnt[10]));
  XNOR2XL g1720(.A (cnt[11]), .B (n_79), .Y (n_86));
  NOR2XL g1721(.A (n_93), .B (n_83), .Y (n_85));
  NOR2XL g1722(.A (n_93), .B (n_80), .Y (n_84));
  DFFQX1 \cnt_reg[13] (.CK (clk), .D (n_81), .Q (cnt[13]));
  AOI21XL g1724(.A0 (cnt[14]), .A1 (n_75), .B0 (n_82), .Y (n_83));
  DFFQX1 \cnt_reg[9] (.CK (clk), .D (n_78), .Q (cnt[9]));
  NOR2XL g1726(.A (cnt[14]), .B (n_75), .Y (n_82));
  NOR2XL g1727(.A (n_93), .B (n_77), .Y (n_81));
  MXI2XL g1728(.A (n_1), .B (cnt[10]), .S0 (n_71), .Y (n_80));
  NOR2XL g1729(.A (n_1), .B (n_71), .Y (n_79));
  NOR2XL g1730(.A (n_93), .B (n_73), .Y (n_78));
  DFFQX1 \cnt_reg[12] (.CK (clk), .D (n_74), .Q (cnt[12]));
  AOI21XL g1732(.A0 (cnt[13]), .A1 (n_68), .B0 (n_76), .Y (n_77));
  DFFQX1 \cnt_reg[8] (.CK (clk), .D (n_70), .Q (cnt[8]));
  NOR2XL g1734(.A (cnt[13]), .B (n_68), .Y (n_76));
  NAND2BX1 g1735(.AN (n_68), .B (cnt[13]), .Y (n_75));
  NOR2XL g1736(.A (n_93), .B (n_69), .Y (n_74));
  AOI21XL g1737(.A0 (cnt[9]), .A1 (n_64), .B0 (n_72), .Y (n_73));
  NOR2XL g1738(.A (cnt[9]), .B (n_64), .Y (n_72));
  NAND2BX1 g1739(.AN (n_64), .B (cnt[9]), .Y (n_71));
  NOR2XL g1740(.A (n_93), .B (n_67), .Y (n_70));
  XNOR2XL g1741(.A (cnt[12]), .B (n_66), .Y (n_69));
  DFFQX1 \cnt_reg[7] (.CK (clk), .D (n_63), .Q (cnt[7]));
  NAND2XL g1743(.A (cnt[12]), .B (n_66), .Y (n_68));
  AOI21XL g1744(.A0 (cnt[8]), .A1 (n_57), .B0 (n_65), .Y (n_67));
  NOR2XL g1746(.A (n_15), .B (n_57), .Y (n_66));
  NOR2XL g1747(.A (cnt[8]), .B (n_57), .Y (n_65));
  NAND2BX1 g1748(.AN (n_57), .B (cnt[8]), .Y (n_64));
  NOR2XL g1749(.A (n_60), .B (n_93), .Y (n_63));
  DFFSHQX1 key_flag_reg(.SN (rst_n), .CK (clk), .D (n_58), .Q
       (key_flag));
  DFFRHQX1 en_cnt_reg(.RN (rst_n), .CK (clk), .D (n_59), .Q (en_cnt));
  DFFQX1 key_stable_reg(.CK (clk), .D (n_61), .Q (key_stable));
  OAI21X1 g1753(.A0 (n_21), .A1 (n_53), .B0 (n_51), .Y (n_62));
  SDFFRHQX1 \state_reg[1] (.RN (rst_n), .CK (clk), .D (state[1]), .SI
       (state[0]), .SE (n_50), .Q (state[1]));
  DFFQX1 \cnt_reg[6] (.CK (clk), .D (n_55), .Q (cnt[6]));
  OAI21X1 g1756(.A0 (n_3), .A1 (n_52), .B0 (n_17), .Y (n_61));
  AOI21XL g1757(.A0 (cnt[7]), .A1 (n_46), .B0 (n_56), .Y (n_60));
  OAI21XL g1758(.A0 (n_22), .A1 (n_25), .B0 (n_54), .Y (n_59));
  AO22XL g1759(.A0 (key_flag), .A1 (n_52), .B0 (n_6), .B1 (n_50), .Y
       (n_58));
  NAND2BX1 g1760(.AN (n_46), .B (cnt[7]), .Y (n_57));
  NOR2XL g1761(.A (cnt[7]), .B (n_46), .Y (n_56));
  NOR2XL g1762(.A (n_48), .B (n_93), .Y (n_55));
  NAND3X1 g1763(.A (en_cnt), .B (n_25), .C (n_52), .Y (n_54));
  AOI21X1 g1764(.A0 (n_20), .A1 (n_49), .B0 (state[0]), .Y (n_53));
  NAND2XL g1765(.A (n_12), .B (n_50), .Y (n_52));
  OAI211X1 g1766(.A0 (n_20), .A1 (n_7), .B0 (n_5), .C0 (n_50), .Y
       (n_51));
  DFFQX1 \cnt_reg[5] (.CK (clk), .D (n_44), .Q (cnt[5]));
  INVXL g1768(.A (n_50), .Y (n_49));
  NAND2XL g1769(.A (n_27), .B (n_45), .Y (n_50));
  AOI21XL g1770(.A0 (cnt[6]), .A1 (n_40), .B0 (n_47), .Y (n_48));
  NOR2XL g1771(.A (cnt[6]), .B (n_40), .Y (n_47));
  NAND2BX1 g1772(.AN (n_40), .B (cnt[6]), .Y (n_46));
  OAI211X1 g1773(.A0 (cnt[6]), .A1 (n_42), .B0 (cnt[10]), .C0 (n_13),
       .Y (n_45));
  NOR2XL g1774(.A (n_43), .B (n_93), .Y (n_44));
  DFFQX1 \cnt_reg[4] (.CK (clk), .D (n_39), .Q (cnt[4]));
  AOI21X1 g1776(.A0 (cnt[5]), .A1 (n_37), .B0 (n_41), .Y (n_43));
  NAND2XL g1777(.A (n_9), .B (n_37), .Y (n_42));
  NOR2XL g1778(.A (cnt[5]), .B (n_37), .Y (n_41));
  NAND2BX1 g1779(.AN (n_37), .B (cnt[5]), .Y (n_40));
  NOR2XL g1780(.A (n_38), .B (n_93), .Y (n_39));
  DFFQX1 \cnt_reg[3] (.CK (clk), .D (n_35), .Q (cnt[3]));
  AOI21X1 g1782(.A0 (cnt[4]), .A1 (n_30), .B0 (n_36), .Y (n_38));
  DFFQX1 \cnt_reg[1] (.CK (clk), .D (n_34), .Q (cnt[1]));
  DFFQX1 \cnt_reg[2] (.CK (clk), .D (n_33), .Q (cnt[2]));
  NAND2BX1 g1785(.AN (n_30), .B (cnt[4]), .Y (n_37));
  NOR2XL g1786(.A (cnt[4]), .B (n_30), .Y (n_36));
  NOR2XL g1787(.A (n_31), .B (n_93), .Y (n_35));
  NOR2XL g1788(.A (n_11), .B (n_93), .Y (n_34));
  NOR2XL g1789(.A (n_23), .B (n_93), .Y (n_33));
  AOI21XL g1791(.A0 (cnt[3]), .A1 (n_18), .B0 (n_29), .Y (n_31));
  NAND2BX1 g1792(.AN (n_18), .B (cnt[3]), .Y (n_30));
  NOR2XL g1793(.A (cnt[3]), .B (n_18), .Y (n_29));
  NOR2XL g1794(.A (cnt[12]), .B (n_24), .Y (n_28));
  OAI31X1 g1795(.A0 (cnt[12]), .A1 (cnt[13]), .A2 (n_16), .B0
       (cnt[14]), .Y (n_27));
  NOR4X1 g1796(.A (cnt[8]), .B (cnt[6]), .C (n_1), .D (n_0), .Y (n_26));
  MXI2XL g1797(.A (n_20), .B (n_21), .S0 (state[0]), .Y (n_25));
  NAND4XL g1798(.A (cnt[1]), .B (cnt[2]), .C (n_9), .D (n_13), .Y
       (n_24));
  AOI21X1 g1799(.A0 (cnt[2]), .A1 (n_4), .B0 (n_19), .Y (n_23));
  XNOR2XL g1800(.A (key_r[2]), .B (state[1]), .Y (n_22));
  NOR2BX1 g1801(.AN (key_r[1]), .B (key_r[2]), .Y (n_21));
  NOR2BX1 g1802(.AN (key_r[2]), .B (key_r[1]), .Y (n_20));
  NOR2XL g1803(.A (cnt[2]), .B (n_4), .Y (n_19));
  NAND2BX1 g1804(.AN (n_4), .B (cnt[2]), .Y (n_18));
  OAI21X1 g1805(.A0 (n_3), .A1 (n_12), .B0 (key_stable), .Y (n_17));
  DFFQX1 \key_r_reg[2] (.CK (clk), .D (key_r[1]), .Q (key_r[2]));
  DFFQX1 \cnt_reg[0] (.CK (clk), .D (n_14), .Q (cnt[0]));
  CLKINVX1 g1809(.A (n_15), .Y (n_16));
  NAND3BX1 g1810(.AN (n_8), .B (cnt[8]), .C (cnt[10]), .Y (n_15));
  DFFQX1 \key_r_reg[1] (.CK (clk), .D (key_r[0]), .Q (key_r[1]));
  NOR2XL g1812(.A (cnt[0]), .B (n_10), .Y (n_14));
  NOR2BX1 g1813(.AN (cnt[14]), .B (n_8), .Y (n_13));
  OR2X1 g1814(.A (n_7), .B (n_6), .Y (n_12));
  XNOR2XL g1815(.A (cnt[1]), .B (cnt[0]), .Y (n_11));
  DFFQX1 \key_r_reg[0] (.CK (clk), .D (key), .Q (key_r[0]));
  NAND2XL g1817(.A (rst_n), .B (en_cnt), .Y (n_10));
  NOR2XL g1818(.A (cnt[5]), .B (cnt[7]), .Y (n_9));
  NAND2XL g1819(.A (cnt[11]), .B (cnt[9]), .Y (n_8));
  NOR2XL g1820(.A (state[1]), .B (n_2), .Y (n_7));
  INVXL g1821(.A (n_5), .Y (n_6));
  NAND2XL g1822(.A (state[1]), .B (n_2), .Y (n_5));
  NAND2XL g1823(.A (cnt[1]), .B (cnt[0]), .Y (n_4));
  CLKINVX1 g1825(.A (rst_n), .Y (n_3));
  CLKINVX1 g1827(.A (cnt[10]), .Y (n_1));
  NAND4BXL g2(.AN (cnt[13]), .B (cnt[0]), .C (cnt[3]), .D (cnt[4]), .Y
       (n_0));
  AO21X1 g1828(.A0 (n_28), .A1 (n_26), .B0 (n_10), .Y (n_93));
  DFFRX1 \state_reg[0] (.RN (rst_n), .CK (clk), .D (n_62), .Q
       (state[0]), .QN (n_2));
endmodule

module led_func(clk, rst_n, flag_os, stable_os, flag_key, stable_key,
     led);
  input clk, rst_n, flag_os, stable_os, flag_key, stable_key;
  output led;
  wire clk, rst_n, flag_os, stable_os, flag_key, stable_key;
  wire led;
  wire [6:0] cnt_1;
  wire [6:0] cnt_3;
  wire [1:0] ledstate;
  wire [6:0] cnt_2;
  wire cnt_full, en_cnt, flag, led_r, n_0, n_1, n_2, n_3;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_40, n_41, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_50, n_51, n_53, n_54, n_55, n_56, n_57, n_58;
  wire n_59, n_60, n_61, n_62, n_63, n_64, n_65, n_66;
  wire n_67, n_68, n_69, n_70, n_71, n_73, n_74, n_75;
  wire n_76, n_77, n_78, n_79, n_81, n_82, n_83, n_84;
  wire n_85, n_86, n_87, n_88, n_89, n_90, n_91, n_92;
  wire n_93, n_94, n_95, n_96, n_97, n_98, n_99, n_101;
  wire n_102, n_103, n_120, n_121, n_123, n_124, n_125, n_126;
  wire n_127, n_128;
  DFFRHQX1 \cnt_1_reg[6] (.RN (rst_n), .CK (clk), .D (n_120), .Q
       (cnt_1[6]));
  DFFRHQX1 \cnt_1_reg[5] (.RN (rst_n), .CK (clk), .D (n_103), .Q
       (cnt_1[5]));
  NOR2XL g2303(.A (n_41), .B (n_102), .Y (n_103));
  DFFRHQX1 \cnt_1_reg[4] (.RN (rst_n), .CK (clk), .D (n_99), .Q
       (cnt_1[4]));
  AOI21X1 g2305(.A0 (cnt_1[5]), .A1 (n_83), .B0 (n_101), .Y (n_102));
  DFFRHQX1 \cnt_3_reg[6] (.RN (rst_n), .CK (clk), .D (n_96), .Q
       (cnt_3[6]));
  DFFRHQX1 \ledstate_reg[0] (.RN (rst_n), .CK (clk), .D (n_97), .Q
       (ledstate[0]));
  NOR2XL g2311(.A (cnt_1[5]), .B (n_83), .Y (n_101));
  NOR2XL g2313(.A (n_87), .B (n_41), .Y (n_99));
  DFFRHQX1 \cnt_3_reg[1] (.RN (rst_n), .CK (clk), .D (n_91), .Q
       (cnt_3[1]));
  DFFRHQX1 \cnt_3_reg[3] (.RN (rst_n), .CK (clk), .D (n_92), .Q
       (cnt_3[3]));
  DFFRHQX1 \cnt_3_reg[5] (.RN (rst_n), .CK (clk), .D (n_88), .Q
       (cnt_3[5]));
  NAND2XL g2319(.A (n_93), .B (n_21), .Y (n_98));
  NAND2XL g2320(.A (n_93), .B (n_28), .Y (n_97));
  OAI2BB1XL g2321(.A0N (cnt_3[6]), .A1N (n_121), .B0 (n_127), .Y
       (n_96));
  NAND2XL g2322(.A (n_93), .B (n_27), .Y (n_95));
  OAI21X1 g2323(.A0 (n_1), .A1 (ledstate[1]), .B0 (n_93), .Y (n_94));
  DFFRHQX1 \cnt_2_reg[6] (.RN (rst_n), .CK (clk), .D (n_81), .Q
       (cnt_2[6]));
  DFFRHQX1 \cnt_1_reg[3] (.RN (rst_n), .CK (clk), .D (n_82), .Q
       (cnt_1[3]));
  SDFFRHQX1 \cnt_3_reg[0] (.RN (rst_n), .CK (clk), .D (n_64), .SI
       (n_46), .SE (cnt_3[0]), .Q (cnt_3[0]));
  NAND3BX1 g2327(.AN (cnt_full), .B (ledstate[0]), .C (ledstate[1]), .Y
       (n_93));
  OAI31X1 g2328(.A0 (cnt_3[3]), .A1 (n_20), .A2 (n_65), .B0 (n_85), .Y
       (n_92));
  OAI31X1 g2329(.A0 (cnt_3[1]), .A1 (n_3), .A2 (n_65), .B0 (n_86), .Y
       (n_91));
  OAI32X1 g2330(.A0 (cnt_3[2]), .A1 (n_13), .A2 (n_65), .B0 (n_123),
       .B1 (n_78), .Y (n_90));
  OAI32X1 g2331(.A0 (cnt_3[4]), .A1 (n_25), .A2 (n_65), .B0 (n_125),
       .B1 (n_77), .Y (n_89));
  OAI31X1 g2332(.A0 (cnt_3[5]), .A1 (n_32), .A2 (n_65), .B0 (n_0), .Y
       (n_88));
  AOI21XL g2333(.A0 (cnt_1[4]), .A1 (n_57), .B0 (n_84), .Y (n_87));
  DFFRHQX1 \cnt_2_reg[1] (.RN (rst_n), .CK (clk), .D (n_75), .Q
       (cnt_2[1]));
  DFFRHQX1 \cnt_2_reg[3] (.RN (rst_n), .CK (clk), .D (n_74), .Q
       (cnt_2[3]));
  DFFRHQX1 \cnt_2_reg[5] (.RN (rst_n), .CK (clk), .D (n_73), .Q
       (cnt_2[5]));
  OAI21X1 g2339(.A0 (n_46), .A1 (n_69), .B0 (cnt_3[1]), .Y (n_86));
  OAI21X1 g2340(.A0 (n_46), .A1 (n_63), .B0 (cnt_3[3]), .Y (n_85));
  NOR2XL g2342(.A (cnt_1[4]), .B (n_57), .Y (n_84));
  NAND2BX1 g2343(.AN (n_57), .B (cnt_1[4]), .Y (n_83));
  NOR2XL g2344(.A (n_61), .B (n_41), .Y (n_82));
  NAND2XL g2345(.A (n_128), .B (n_79), .Y (n_81));
  DFFRHQX1 cnt_full_reg(.RN (rst_n), .CK (clk), .D (n_62), .Q
       (cnt_full));
  SDFFRHQX1 \cnt_2_reg[0] (.RN (rst_n), .CK (clk), .D (n_48), .SI
       (n_40), .SE (cnt_2[0]), .Q (cnt_2[0]));
  OAI21X1 g2349(.A0 (n_37), .A1 (n_55), .B0 (cnt_2[6]), .Y (n_79));
  AOI21X1 g2350(.A0 (n_13), .A1 (n_59), .B0 (n_46), .Y (n_78));
  AOI21X1 g2351(.A0 (n_25), .A1 (n_59), .B0 (n_46), .Y (n_77));
  AOI21X1 g2353(.A0 (n_32), .A1 (n_59), .B0 (n_46), .Y (n_76));
  OAI31X1 g2354(.A0 (cnt_2[1]), .A1 (n_7), .A2 (n_47), .B0 (n_68), .Y
       (n_75));
  OAI31X1 g2355(.A0 (cnt_2[3]), .A1 (n_19), .A2 (n_47), .B0 (n_67), .Y
       (n_74));
  OAI31X1 g2356(.A0 (cnt_2[5]), .A1 (n_31), .A2 (n_47), .B0 (n_66), .Y
       (n_73));
  OAI32X1 g2358(.A0 (cnt_2[2]), .A1 (n_12), .A2 (n_47), .B0 (n_2), .B1
       (n_54), .Y (n_71));
  OAI32X1 g2359(.A0 (cnt_2[4]), .A1 (n_24), .A2 (n_47), .B0 (n_124),
       .B1 (n_53), .Y (n_70));
  DFFRHQX1 \cnt_1_reg[2] (.RN (rst_n), .CK (clk), .D (n_56), .Q
       (cnt_1[2]));
  NOR2XL g2361(.A (cnt_3[0]), .B (n_60), .Y (n_69));
  OAI21X1 g2362(.A0 (n_40), .A1 (n_50), .B0 (cnt_2[1]), .Y (n_68));
  OAI21X1 g2363(.A0 (n_40), .A1 (n_44), .B0 (cnt_2[3]), .Y (n_67));
  NAND2XL g2364(.A (cnt_2[5]), .B (n_55), .Y (n_66));
  CLKINVX1 g2365(.A (n_65), .Y (n_64));
  NAND2XL g2366(.A (n_36), .B (n_59), .Y (n_65));
  NOR2BX1 g2367(.AN (n_20), .B (n_60), .Y (n_63));
  NOR3BX1 g2368(.AN (n_36), .B (n_1), .C (n_43), .Y (n_62));
  AOI21XL g2369(.A0 (cnt_1[3]), .A1 (n_33), .B0 (n_58), .Y (n_61));
  DFFRHQX1 \cnt_1_reg[1] (.RN (rst_n), .CK (clk), .D (n_45), .Q
       (cnt_1[1]));
  DFFRHQX1 \cnt_1_reg[0] (.RN (rst_n), .CK (clk), .D (n_51), .Q
       (cnt_1[0]));
  CLKINVX1 g2372(.A (n_60), .Y (n_59));
  NAND2XL g2373(.A (en_cnt), .B (n_43), .Y (n_60));
  NOR2XL g2374(.A (cnt_1[3]), .B (n_33), .Y (n_58));
  NAND2BX1 g2375(.AN (n_33), .B (cnt_1[3]), .Y (n_57));
  NOR2XL g2376(.A (n_35), .B (n_41), .Y (n_56));
  OAI2BB1X1 g2377(.A0N (n_37), .A1N (n_31), .B0 (n_41), .Y (n_55));
  AOI21X1 g2378(.A0 (n_12), .A1 (n_37), .B0 (n_40), .Y (n_54));
  AOI21X1 g2379(.A0 (n_24), .A1 (n_37), .B0 (n_40), .Y (n_53));
  NOR2XL g2381(.A (cnt_1[0]), .B (n_41), .Y (n_51));
  NOR2XL g2382(.A (cnt_2[0]), .B (n_38), .Y (n_50));
  CLKINVX1 g2384(.A (n_48), .Y (n_47));
  NOR2XL g2385(.A (n_30), .B (n_38), .Y (n_48));
  NOR2XL g2386(.A (n_1), .B (n_36), .Y (n_46));
  NOR2XL g2387(.A (n_16), .B (n_41), .Y (n_45));
  NOR2BX1 g2388(.AN (n_19), .B (n_38), .Y (n_44));
  OAI211X1 g2389(.A0 (cnt_3[4]), .A1 (n_23), .B0 (cnt_3[6]), .C0
       (cnt_3[5]), .Y (n_43));
  DFFRHQX1 flag_reg(.RN (rst_n), .CK (clk), .D (n_26), .Q (flag));
  CLKINVX1 g2392(.A (n_41), .Y (n_40));
  NAND2XL g2393(.A (en_cnt), .B (n_30), .Y (n_41));
  CLKINVX1 g2395(.A (n_38), .Y (n_37));
  NAND2XL g2396(.A (en_cnt), .B (n_29), .Y (n_38));
  NOR2XL g2397(.A (n_30), .B (n_29), .Y (n_36));
  AOI21X1 g2398(.A0 (cnt_1[2]), .A1 (n_9), .B0 (n_34), .Y (n_35));
  NOR2XL g2399(.A (cnt_1[2]), .B (n_9), .Y (n_34));
  NAND2BX1 g2400(.AN (n_9), .B (cnt_1[2]), .Y (n_33));
  NAND2BX1 g2401(.AN (n_25), .B (cnt_3[4]), .Y (n_32));
  NAND2BX1 g2402(.AN (n_24), .B (cnt_2[4]), .Y (n_31));
  OAI211X1 g2403(.A0 (cnt_1[4]), .A1 (n_15), .B0 (cnt_1[6]), .C0
       (cnt_1[5]), .Y (n_30));
  OAI211X1 g2404(.A0 (cnt_2[4]), .A1 (n_14), .B0 (cnt_2[6]), .C0
       (cnt_2[5]), .Y (n_29));
  OAI21X1 g2405(.A0 (n_10), .A1 (n_18), .B0 (n_11), .Y (n_28));
  NAND3BX1 g2406(.AN (n_10), .B (n_11), .C (n_18), .Y (n_27));
  AO22XL g2407(.A0 (ledstate[0]), .A1 (n_17), .B0 (flag), .B1 (n_11),
       .Y (n_26));
  NAND2BX1 g2408(.AN (n_20), .B (cnt_3[3]), .Y (n_25));
  NAND2BX1 g2409(.AN (n_19), .B (cnt_2[3]), .Y (n_24));
  CLKINVX1 g2410(.A (n_22), .Y (n_23));
  OAI31X1 g2411(.A0 (cnt_3[1]), .A1 (cnt_3[2]), .A2 (cnt_3[0]), .B0
       (cnt_3[3]), .Y (n_22));
  AOI32XL g2412(.A0 (n_8), .A1 (ledstate[0]), .A2 (flag), .B0 (n_11),
       .B1 (led_r), .Y (n_21));
  NAND2BX1 g2413(.AN (n_13), .B (cnt_3[2]), .Y (n_20));
  NAND2BX1 g2414(.AN (n_12), .B (cnt_2[2]), .Y (n_19));
  NOR3BX1 g2415(.AN (stable_os), .B (flag), .C (flag_os), .Y (n_18));
  MXI2XL g2416(.A (ledstate[1]), .B (n_8), .S0 (flag), .Y (n_17));
  XNOR2XL g2417(.A (cnt_1[1]), .B (cnt_1[0]), .Y (n_16));
  OR2XL g2418(.A (cnt_1[2]), .B (cnt_1[3]), .Y (n_15));
  NAND2BX1 g2419(.AN (cnt_2[3]), .B (n_2), .Y (n_14));
  NAND2XL g2420(.A (cnt_3[1]), .B (cnt_3[0]), .Y (n_13));
  NAND2XL g2421(.A (cnt_2[0]), .B (cnt_2[1]), .Y (n_12));
  NOR2XL g2422(.A (ledstate[0]), .B (ledstate[1]), .Y (n_11));
  NOR2BX1 g2423(.AN (stable_key), .B (flag_key), .Y (n_10));
  NAND2XL g2424(.A (cnt_1[0]), .B (cnt_1[1]), .Y (n_9));
  INVXL g2426(.A (cnt_2[0]), .Y (n_7));
  INVXL g2430(.A (cnt_3[0]), .Y (n_3));
  NAND2BX1 g2(.AN (n_76), .B (cnt_3[5]), .Y (n_0));
  AOI2BB1XL g2437(.A0N (cnt_1[6]), .A1N (n_126), .B0 (n_41), .Y
       (n_120));
  NAND2XL g2438(.A (n_60), .B (n_76), .Y (n_121));
  DFFRX1 led_r_reg(.RN (rst_n), .CK (clk), .D (n_98), .Q (led_r), .QN
       (led));
  DFFRX1 \ledstate_reg[1] (.RN (rst_n), .CK (clk), .D (n_95), .Q
       (ledstate[1]), .QN (n_8));
  DFFRX1 \cnt_3_reg[2] (.RN (rst_n), .CK (clk), .D (n_90), .Q
       (cnt_3[2]), .QN (n_123));
  DFFRX1 \cnt_2_reg[4] (.RN (rst_n), .CK (clk), .D (n_70), .Q
       (cnt_2[4]), .QN (n_124));
  DFFRX1 \cnt_3_reg[4] (.RN (rst_n), .CK (clk), .D (n_89), .Q
       (cnt_3[4]), .QN (n_125));
  DFFRX1 \cnt_2_reg[2] (.RN (rst_n), .CK (clk), .D (n_71), .Q
       (cnt_2[2]), .QN (n_2));
  DFFRX1 en_cnt_reg(.RN (rst_n), .CK (clk), .D (n_94), .Q (en_cnt), .QN
       (n_1));
  NOR2BXL g2453(.AN (cnt_1[5]), .B (n_83), .Y (n_126));
  NAND3BX1 g2454(.AN (n_32), .B (cnt_3[5]), .C (n_64), .Y (n_127));
  NAND3BX1 g2455(.AN (n_31), .B (cnt_2[5]), .C (n_48), .Y (n_128));
endmodule

module led_top(clk, rst_n, key_os, key_key, led);
  input clk, rst_n, key_os, key_key;
  output led;
  wire clk, rst_n, key_os, key_key;
  wire led;
  wire flag_key, flag_os, stable_key, stable_os;
  key_filter_1 filter_key(.clk (clk), .rst_n (rst_n), .key (key_key),
       .key_stable (stable_key), .key_flag (flag_key));
  key_filter filter_os(.clk (clk), .rst_n (rst_n), .key (key_os),
       .key_stable (stable_os), .key_flag (flag_os));
  led_func led_func(.clk (clk), .rst_n (rst_n), .flag_os (flag_os),
       .stable_os (stable_os), .flag_key (flag_key), .stable_key
       (stable_key), .led (led));
endmodule

